Repository thirvusoft/core_accounting, pull requests merged in 2022-08, with the labels that each got.

#14 Tax amount fetching itemwise
  core_accounting/core_accounting/doctype/core_accounting_settings/core_accounting_settings.json
  core_accounting/hooks.py
  core_accounting/patches/py/custom_field.py
  core_accounting/patches/py/item_tax_percentage.py
Labels: enhancement

#15 Chores:bug fix
  core_accounting/hooks.py
Labels: bug fix

#16 tax table error fix
  core_accounting/patches/py/item_tax_percentage.py
Labels: bug
